# Generated by Django 2.2 on 2019-04-29 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('replicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replica',
            name='cpu',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replica',
            name='io',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replica',
            name='memory',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
