# Generated by Django 2.2 on 2019-04-29 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('replicas', '0003_auto_20190429_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='replica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='replicas.Replica'),
            preserve_default=False,
        ),
    ]
